import type { Metadata } from "next";
import "../styles/globals.css";
import Providers from "@/modules/providers";

export const metadata: Metadata = {
  title: "POS System",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-[#f0f5f3]">
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
